spring:
  data:
    cassandra:
      port: 9142
      cluster-name: 127.0.0.1
      keyspace-name: dvr
  jpa:
    show-sql: true
  #cache:
  #  type: redis
  redis:
    host: localhost
    port: 6379
server:
  port: 7788

#logging:
#  level: debug
